### ISSUE TITLE
Tool crashes

### ISSUE THREAD

**Issue by SharePointOscar** [dropbox/DropboxBusinessAdminTool#32]
I tried using it to audit my team.  Used a CSV file to only audit a subset of members.  The tool just crashes on Windows 10.

**Comment by macribas** [comment]
I'm getting crashes when trying to use the Team Auditing tab as well.

**Comment by shamilrocks** [comment]
Crashing on team auditing tab as well.

**Comment by shamilrocks** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          8/21/2017 1:21:33 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-5SD62BT
Description:
Application: DfBAdminToolkit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon)
   at DfBAdminToolkit.Presenter.TeamAuditingPresenter.GetEvents(DfBAdminToolkit.Model.ITeamAuditingModel, DfBAdminToolkit.View.ITeamAuditingView, DfBAdminToolkit.Presenter.IMainPresenter)
   at DfBAdminToolkit.Presenter.TeamAuditingPresenter+<>c__DisplayClass14_0.<OnCommandLoadEvents>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-08-21T17:21:33.444427800Z" />
    <EventRecordID>109466</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-5SD62BT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: DfBAdminToolkit.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Runtime.CompilerServices.CallSite, System.__Canon)
   at DfBAdminToolkit.Presenter.TeamAuditingPresenter.GetEvents(DfBAdminToolkit.Model.ITeamAuditingModel, DfBAdminToolkit.View.ITeamAuditingView, DfBAdminToolkit.Presenter.IMainPresenter)
   at DfBAdminToolkit.Presenter.TeamAuditingPresenter+&lt;&gt;c__DisplayClass14_0.&lt;OnCommandLoadEvents&gt;b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by jackb-dropbox** [comment]
This is fixed in new release, change in API broke things for event categories

**Comment by SharePointOscar** [comment]
Thanks @jackb-dropbox :)
